server:
  port: 8081
spring:
  redis:
    host: 121.4.41.89
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

